version: 2

project_name: meshd

before:
  hooks:
    - go mod tidy

builds:
  - id: meshd
    main: ./cmd/meshd/
    binary: meshd
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - id: meshd
    formats: ['tar.gz']
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-dev"

changelog:
  disable: true
